import { FormEvent, useState } from 'react';
import { API } from '../shared/api';
import type { Session } from '../shared/types';

export function Login({ onLogin }: { onLogin: (session: Session, remember: boolean) => void }) {
  const [signup,setSignup]=useState(false),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[firstName,setFirstName]=useState(''),[lastName,setLastName]=useState(''),[phone,setPhone]=useState(''),[show,setShow]=useState(false),[remember,setRemember]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[dark,setDark]=useState(true);
  async function submit(e: FormEvent) { e.preventDefault(); setBusy(true); setError(''); try { const body=signup?{firstName,lastName,email,password,phone}:{email,password}; const response=await fetch(`${API}/api/auth/${signup?'signup':'login'}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}); if(!response.ok){const data=await response.json().catch(()=>({}));throw new Error(data.message)} onLogin(await response.json(),remember); } catch(e) { setError(e instanceof Error&&e.message?e.message:(signup?'Unable to create your account.':'Invalid credentials.')); } finally { setBusy(false); } }
  return <main className={dark?'login dark':'login'}><section className="login-art"><div className="logo">BFPME <span>Recruit</span></div><div><span className="pill">SECURE TALENT OPERATIONS</span><h1>{signup?'Your next opportunity starts here.':'Build the team that builds the future.'}</h1><p>{signup?'Create your candidate account, discover opportunities, and follow your applications.':'A focused workspace for hiring teams, evaluators, and recruitment leaders.'}</p></div><small>Protected with role-based access and secure sessions.</small></section><section className="login-panel"><button className="theme" onClick={()=>setDark(!dark)} aria-label="Toggle theme">{dark?'☀':'☾'}</button><form onSubmit={submit}><div className="mini-logo">BF</div><h2>{signup?'Create your account':'Welcome back'}</h2><p>{signup?'Register as a candidate.':'Sign in to your recruitment workspace.'}</p>{error&&<div className="alert">{error}</div>}{signup&&<div className="two"><label>First name<input value={firstName} onChange={e=>setFirstName(e.target.value)} required/></label><label>Last name<input value={lastName} onChange={e=>setLastName(e.target.value)} required/></label></div>}<label>Email address<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required autoComplete="email"/></label>{signup&&<label>Phone <small>(optional)</small><input value={phone} onChange={e=>setPhone(e.target.value)}/></label>}<label>Password<div className="password"><input type={show?'text':'password'} value={password} onChange={e=>setPassword(e.target.value)} minLength={signup?12:1} required/><button type="button" onClick={()=>setShow(!show)}>{show?'Hide':'Show'}</button></div></label><div className="form-row"><label className="check"><input type="checkbox" checked={remember} onChange={e=>setRemember(e.target.checked)}/> Remember me</label></div><button className="primary" disabled={busy}>{busy?'Please wait…':signup?'Create candidate account':'Sign in'}</button><button className="auth-toggle" type="button" onClick={()=>{setSignup(!signup);setError('')}}>{signup?'Already registered? Sign in':'Candidate? Create an account'}</button><small className="security">Internal accounts are provisioned by an administrator.</small></form></section></main>;
}
