import { useEffect, useState } from 'react';
import { API, authHeaders } from './api';
import type { Session } from './types';
import './Complaints.css';

type Status = 'PENDING' | 'IN_PROGRESS' | 'RESOLVED' | 'CLOSED';
type Complaint = { id: number; subject: string; message: string; category: string; status: Status; createdAt: string; response?: string; respondedAt?: string; userName: string; userEmail: string; userRole: string };
const statuses: Status[] = ['PENDING', 'IN_PROGRESS', 'RESOLVED', 'CLOSED'];
const pretty = (value: string) => value.replaceAll('_', ' ');
const date = (value?: string) => value ? new Date(value).toLocaleString() : 'Not available';
export function AdminComplaintsPage({ session }: { session: Session }) {
  const [items, setItems] = useState<Complaint[]>([]), [selected, setSelected] = useState<Complaint | null>(null), [filter, setFilter] = useState(''), [query, setQuery] = useState(''), [response, setResponse] = useState(''), [newStatus, setNewStatus] = useState<Status>('PENDING'), [error, setError] = useState('');
  const load = async () => { const params = filter ? `?status=${filter}` : ''; const result = await fetch(`${API}/api/admin/complaints${params}`, { headers: authHeaders(session.accessToken) }); if (!result.ok) throw new Error('Could not load complaints.'); setItems(await result.json()); };
  useEffect(() => { void load().catch(err => setError(err.message)); }, [filter]);
  const open = (item: Complaint) => { setSelected(item); setResponse(item.response || ''); setNewStatus(item.status); };
  const update = async (path: string, body: object) => { const result = await fetch(`${API}${path}`, { method: path.includes('status') ? 'PATCH' : 'POST', headers: authHeaders(session.accessToken), body: JSON.stringify(body) }); if (!result.ok) { const data = await result.json().catch(() => ({})); throw new Error(data.message || 'Update failed.'); } const updated = await result.json(); setItems(current => current.map(item => item.id === updated.id ? updated : item)); setSelected(updated); };
  const filtered = items.filter(item => `${item.subject} ${item.userName} ${item.userEmail} ${item.category}`.toLowerCase().includes(query.toLowerCase()));
  return <section className="complaints-page"><header className="complaints-header"><div><small>ADMINISTRATION</small><h1>Complaint Management</h1><p>Review, respond to, and resolve user complaints.</p></div></header>{error && <div className="complaint-alert">{error}</div>}<div className="complaint-tools"><input placeholder="Search complaints..." value={query} onChange={event => setQuery(event.target.value)} />{['', ...statuses].map(item => <button key={item} className={filter === item ? 'active' : ''} onClick={() => setFilter(item)}>{item ? pretty(item) : 'All'}</button>)}</div><div className="admin-complaint-table"><div className="admin-row admin-head"><span>User</span><span>Role</span><span>Subject</span><span>Category</span><span>Status</span><span>Date</span></div>{filtered.map(item => <button className="admin-row" key={item.id} onClick={() => open(item)}><span><b>{item.userName}</b><small>{item.userEmail}</small></span><span>{item.userRole}</span><span>{item.subject}</span><span>{pretty(item.category)}</span><span><em className={`status ${item.status.toLowerCase()}`}>{pretty(item.status)}</em></span><span>{date(item.createdAt)}</span></button>)}</div>{selected && <div className="complaint-overlay" onMouseDown={event => event.target === event.currentTarget && setSelected(null)}><article className="complaint-detail admin-detail"><button className="close" onClick={() => setSelected(null)}>×</button><small>COMPLAINT #{selected.id}</small><h2>{selected.subject}</h2><p><b>User:</b> {selected.userName} ({selected.userRole})</p><p><b>Email:</b> {selected.userEmail}</p><p><b>Created:</b> {date(selected.createdAt)}</p><div className="message"><b>Message</b><p>{selected.message}</p></div><label>Admin response<textarea rows={5} value={response} onChange={event => setResponse(event.target.value)} /></label><button className="primary" disabled={!response.trim()} onClick={() => void update(`/api/admin/complaints/${selected.id}/response`, { response }).catch(err => setError(err.message))}>Send Response</button><label>Status<select value={newStatus} onChange={event => setNewStatus(event.target.value as Status)}>{statuses.map(item => <option key={item}>{item}</option>)}</select></label><button onClick={() => void update(`/api/admin/complaints/${selected.id}/status`, { status: newStatus }).catch(err => setError(err.message))}>Update Status</button></article></div>}</section>;
}
