import { FormEvent, useEffect, useState } from 'react';
import { API, authHeaders } from './api';
import type { Session } from './types';
import './Complaints.css';

type Category = 'TECHNICAL' | 'RECRUITMENT' | 'APPLICATION' | 'INTERVIEW' | 'ACCOUNT' | 'OTHER';
type Status = 'PENDING' | 'IN_PROGRESS' | 'RESOLVED' | 'CLOSED';
type Complaint = { id: number; subject: string; message: string; category: Category; status: Status; createdAt: string; response?: string; respondedAt?: string };
const categories: Category[] = ['TECHNICAL', 'RECRUITMENT', 'APPLICATION', 'INTERVIEW', 'ACCOUNT', 'OTHER'];
const pretty = (value: string) => value.replaceAll('_', ' ');
const date = (value?: string) => value ? new Date(value).toLocaleString() : 'Not available';

export function ComplaintsPage({ session, logout }: { session: Session; logout: () => void }) {
  const [items, setItems] = useState<Complaint[]>([]), [selected, setSelected] = useState<Complaint | null>(null), [form, setForm] = useState({ subject: '', category: '' as Category | '', message: '' }), [busy, setBusy] = useState(false), [loading, setLoading] = useState(true), [error, setError] = useState(''), [success, setSuccess] = useState('');
  const load = async () => { setLoading(true); try { const response = await fetch(`${API}/api/complaints/my`, { headers: authHeaders(session.accessToken) }); if (response.status === 401) return logout(); if (!response.ok) throw new Error('Could not load complaints.'); setItems(await response.json()); } catch (err) { setError(err instanceof Error ? err.message : 'Could not load complaints.'); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const submit = async (event: FormEvent) => { event.preventDefault(); setBusy(true); setError(''); setSuccess(''); try { const response = await fetch(`${API}/api/complaints`, { method: 'POST', headers: authHeaders(session.accessToken), body: JSON.stringify(form) }); const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body.message || 'Could not submit complaint.'); setForm({ subject: '', category: '', message: '' }); setSuccess('Your complaint has been submitted successfully.'); await load(); } catch (err) { setError(err instanceof Error ? err.message : 'Could not submit complaint.'); } finally { setBusy(false); } };
  return <section className="complaints-page"><header className="complaints-header"><div><small>SUPPORT</small><h1>Complaints</h1><p>Contact the administration and follow up on your requests.</p></div></header>{error && <div className="complaint-alert">{error}</div>}{success && <div className="complaint-success">{success}</div>}<div className="complaints-grid"><form className="complaint-form" onSubmit={submit}><h2>New Complaint</h2><label>Subject<input required maxLength={200} value={form.subject} onChange={event => setForm({ ...form, subject: event.target.value })} /></label><label>Category<select required value={form.category} onChange={event => setForm({ ...form, category: event.target.value as Category })}><option value="">Select category</option>{categories.map(item => <option key={item}>{pretty(item)}</option>)}</select></label><label>Message<textarea required minLength={10} maxLength={10000} rows={7} value={form.message} onChange={event => setForm({ ...form, message: event.target.value })} /></label><button className="primary" disabled={busy}>{busy ? 'Submitting...' : 'Submit Complaint'}</button></form><div className="complaints-list"><h2>My Complaints</h2>{loading ? <p>Loading...</p> : !items.length ? <p className="muted">No complaints submitted yet.</p> : items.map(item => <button className="complaint-row" key={item.id} onClick={() => setSelected(item)}><span><b>{item.subject}</b><small>{pretty(item.category)} · {date(item.createdAt)}</small></span><em className={`status ${item.status.toLowerCase()}`}>{pretty(item.status)}</em></button>)}</div></div>{selected && <div className="complaint-overlay" onMouseDown={event => event.target === event.currentTarget && setSelected(null)}><article className="complaint-detail"><button className="close" onClick={() => setSelected(null)}>×</button><small>COMPLAINT #{selected.id}</small><h2>{selected.subject}</h2><p><b>Category:</b> {pretty(selected.category)}</p><p><b>Status:</b> <em className={`status ${selected.status.toLowerCase()}`}>{pretty(selected.status)}</em></p><p><b>Created:</b> {date(selected.createdAt)}</p><div className="message"><b>Message</b><p>{selected.message}</p></div><div className="message"><b>Response from Administration</b><p>{selected.response || 'No response yet.'}</p>{selected.respondedAt && <small>Responded {date(selected.respondedAt)}</small>}</div></article></div>}</section>;
}
