import { FormEvent, useEffect, useMemo, useState } from 'react';
import { API, authHeaders } from '../shared/api';
import type { InternalUser, Session } from '../shared/types';

export function AdminDashboard({session,logout}:{session:Session;logout:()=>void}) {
 const [users,setUsers]=useState<InternalUser[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[modal,setModal]=useState(false),[query,setQuery]=useState(''),[role,setRole]=useState(''),[status,setStatus]=useState(''); const headers=authHeaders(session.accessToken);
 async function load(){setLoading(true);try{const p=new URLSearchParams();if(role)p.set('role',role);if(status)p.set('status',status);if(query)p.set('name',query);const r=await fetch(`${API}/api/admin/users?${p}`,{headers});if(r.status===401)return logout();if(!r.ok)throw new Error();setUsers(await r.json());setError('')}catch{setError('Could not load team members.')}finally{setLoading(false)}}
 useEffect(()=>{void load()},[role,status]);
 async function action(u:InternalUser,kind:'disable'|'activate'|'delete'){if(!confirm(`Are you sure you want to ${kind} ${u.firstName} ${u.lastName}'s account?`))return;const r=await fetch(`${API}/api/admin/users/${u.id}/${kind==='delete'?'':kind}`.replace(/\/$/,''),{method:kind==='delete'?'DELETE':'PATCH',headers});if(r.ok)void load();else setError('The account could not be updated.')}
 const counts=useMemo(()=>({active:users.filter(u=>u.status==='ACTIVE').length,hr:users.filter(u=>u.role==='HR').length,evaluator:users.filter(u=>u.role==='EVALUATOR').length}),[users]);
 return <div className="shell"><aside><div className="side-logo">BF<span>Recruit</span></div><nav><b>WORKSPACE</b><button className="active">▦ User management</button><button>◫ Recruitment</button><button>◇ Evaluations</button><button>◌ Reports</button></nav><div className="profile"><span>{session.firstName[0]}{session.lastName[0]}</span><div><b>{session.firstName} {session.lastName}</b><small>Administrator</small></div><button onClick={logout}>↗</button></div></aside><main className="content"><header><div><small>ADMINISTRATION</small><h1>User management</h1><p>Manage access for your internal recruitment team.</p></div><button className="primary add" onClick={()=>setModal(true)}>＋ Add team member</button></header><section className="stats"><article><span>Active accounts</span><b>{counts.active}</b><i className="green">↗ Secure</i></article><article><span>HR team</span><b>{counts.hr}</b><i>Human resources</i></article><article><span>Evaluators</span><b>{counts.evaluator}</b><i>Assessment team</i></article></section><section className="table-card"><div className="tools"><form onSubmit={e=>{e.preventDefault();void load()}}><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search by name…"/></form><select value={role} onChange={e=>setRole(e.target.value)}><option value="">All roles</option><option>HR</option><option>EVALUATOR</option></select><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option><option>ACTIVE</option><option>DISABLED</option><option>BLOCKED</option></select></div>{error&&<div className="alert">{error}</div>}<div className="table"><div className="tr head"><span>Name</span><span>Email</span><span>Role</span><span>Status</span><span>Created</span><span>Actions</span></div>{loading?<div className="loading">Loading team…</div>:users.length===0?<div className="loading">No accounts match these filters.</div>:users.map(u=><div className="tr" key={u.id}><span className="person"><i>{u.firstName[0]}{u.lastName[0]}</i><b>{u.firstName} {u.lastName}</b></span><span>{u.email}</span><span><em>{u.role==='EVALUATOR'?'Evaluator':'HR'}</em></span><span><em className={u.status.toLowerCase()}>● {u.status.toLowerCase()}</em></span><span>{new Date(u.createdAt).toLocaleDateString()}</span><span className="actions">{u.status==='ACTIVE'?<button onClick={()=>action(u,'disable')}>Disable</button>:<button onClick={()=>action(u,'activate')}>Activate</button>}<button className="danger" onClick={()=>action(u,'delete')}>Delete</button></span></div>)}</div></section></main>{modal&&<AddUser headers={headers} close={()=>setModal(false)} done={()=>{setModal(false);void load()}}/>}</div>;
}

function AddUser({headers,close,done}:{headers:Record<string,string>;close:()=>void;done:()=>void}){const [form,setForm]=useState({firstName:'',lastName:'',email:'',password:'',role:'HR'}),[error,setError]=useState(''),[busy,setBusy]=useState(false);async function submit(e:FormEvent){e.preventDefault();setBusy(true);const r=await fetch(`${API}/api/admin/users`,{method:'POST',headers,body:JSON.stringify(form)});if(r.ok)return done();const body=await r.json().catch(()=>({}));setError(body.message||'Could not create this account.');setBusy(false)}return <div className="overlay" onMouseDown={e=>e.target===e.currentTarget&&close()}><form className="modal" onSubmit={submit}><button type="button" className="close" onClick={close}>×</button><small>NEW INTERNAL ACCOUNT</small><h2>Add team member</h2>{error&&<div className="alert">{error}</div>}<div className="two"><label>First name<input required value={form.firstName} onChange={e=>setForm({...form,firstName:e.target.value})}/></label><label>Last name<input required value={form.lastName} onChange={e=>setForm({...form,lastName:e.target.value})}/></label></div><label>Email<input type="email" required value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label>Role<select value={form.role} onChange={e=>setForm({...form,role:e.target.value})}><option value="HR">HR</option><option value="EVALUATOR">Evaluator</option></select></label><label>Temporary password<input type="password" minLength={12} required value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></label><div className="modal-actions"><button type="button" onClick={close}>Cancel</button><button className="primary" disabled={busy}>{busy?'Creating…':'Create account'}</button></div></form></div>}
